apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-ingress
  annotations:
spec:
  rules:
    - host: websocket.52xiaojuzi.top
      http:
        paths:
          - path: echo/
            pathType: Prefix
            backend:
              service:
                name: websocket
                port:
                  number: 80
